# Generated by Django 3.2 on 2022-10-29 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20221028_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='online',
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=12),
        ),
        migrations.AddField(
            model_name='room',
            name='online_users',
            field=models.ManyToManyField(blank=True, to='chat.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.user'),
        ),
    ]
